### ISSUE TITLE
Trackpad scrolling

### ISSUE THREAD

**Issue by jhmatthews** [astro-soton/astroweb#3]

**Comment by chrisfrohmaier** [comment]
in `animate.css` I commented out `overflow: hidden`

``` html
html, body {
    /*overflow: hidden;*/ 
}
```

Problem fixed

**Comment by chrisfrohmaier** [comment]
Fixed in commit e008601

**Comment by chrisfrohmaier** [comment]
Balls, worked locally, didn't work when tried it on the online version
